App/urls.py
from . import views 
from django.urls import path

urlpatterns = [
   path('',views.Home,name='home'),
   path('logout/',views.Logout,name='logout'),
   path('customer-signup/',views.customer_signup, name='customer_signup'),
   path('customer-login/',views.customer_login.as_view(), name='customer_login'),
   path('product-detail/<int:pk>/',views.product_detail,name='product_detail'),
   #path('product-cart/',views.product_cart,name='product_cart'),

   path ('order-summary', views.OrderSummaryView.as_view(), name='order-summary'),
   path ('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
   path ('remove-from-cart/<int:pk>/', views.remove_from_cart, name='remove-from-cart'),
   path ('reduce-quantity-item/<int:pk>/', views.reduce_quantity_item, name='reduce-quantity-item'),
   path('account/',views.customer_account,name='customer-account'),
   path('customer/address/create/',views.create_customer_address,name='create-customer-address'),
 
   path ('checkout/', views.CheckoutView.as_view(), name='checkout'),
   path ('payment/', views.PaymentView.as_view(), name='payment'),
   path('customer/checkout/address/',views.CheckoutAddress.as_view(),name = 'checkout-address'),
   path('save-product/<int:productId>/',views.save_product,name='save-product'),
   path('remove-save-product/<int:productId>/',views.remove_save_product,name='save-product'),
   path('save-later/',views.SaveLater,name='save-later'),

   path('seller-login/',views.seller_login.as_view(),name='seller-login'),
   path('seller-signup/',views.seller_signup,name='seller-signup'),
   path('seller-dashboard/',views.seller_dashboard,name='seller-dashboard'),
   path('seller-orders/',views.seller_orders,name='seller-orders'),
   path('seller-customer/',views.seller_customer,name='seller-customer'),
   path('seller-settings/',views.seller_settings,name='seller-settings'),
   path('create-product/',views.create_product,name='create-product'),
   path('product-list/',views.product_list,name='product-list'),
   path('edit-product/<int:pk>/',views.edit_product,name='edit-product'),

   
]

DiasporaBlack/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('App.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.conf import settings
from .manager import *
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


# Create your models here.

class myuser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)
    is_customer = models.BooleanField(default= False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return f'{self.first_name} {self.last_name}'





class Region(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'

class City(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    name = models.CharField(max_length= 100)

    def __str__(self):
        return f'{self.name}'

Gender = [
    ('Male', 'Male'),
    ('Female', 'Female'),
]

class Customer(models.Model):
    user = models.OneToOneField(myuser, on_delete=models.CASCADE)
    gender = models.CharField(max_length= 100, choices=Gender, null=False, blank= False)
    birth_date = models.DateField(null=False, blank= False)
    phone_number = models.CharField(max_length= 100, null=False, blank= False)
    profile_image =models.ImageField(upload_to ='profile_image/')
    delivery_address = models.CharField(max_length=100, null =False, blank = False)
    region = models.ForeignKey(Region, on_delete =models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)


BusinessModel =[
    ('Individual', 'Individual'),
    ('Company', 'Company'),
    ('Registered Business Name', 'Registered Business Name'),
]

class Seller(models.Model):
    user = models.OneToOneField(myuser, on_delete= models.CASCADE)
    shop_name = models.CharField(max_length= 100,unique=True)
    business_type = models.CharField(max_length= 100, choices= BusinessModel, null=False,blank=False, help_text='Please select if you are an individual or Business Entity/Company')
    phone_number = models.CharField(max_length=20, null =False, blank = False)
    profile_image =models.ImageField(upload_to ='seller-image/',null=True,blank=True)
    address = models.CharField(max_length=100, null =False, blank = False)
    region = models.ForeignKey(Region, on_delete =models.CASCADE,null=True,blank=True)
    city = models.ForeignKey(City, on_delete= models.CASCADE)
    bank_name = models.CharField(max_length = 100)
    account_name = models.CharField(max_length = 100)
    account_number = models.CharField(max_length = 11,null=True)

    def __str__(self):
        return f'{self.shop_name}'

class Categories(models.Model):
    title = models.CharField(max_length =100)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name_plural = 'Categories'

class SubCategories(models.Model):
    category = models.ForeignKey(Categories, on_delete= models.CASCADE)
    title = models.CharField(max_length= 100)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name_plural = 'SubCategories'

class Product(models.Model):
    category = models.ForeignKey(Categories, on_delete = models.CASCADE)
    sub_category = models.ForeignKey(SubCategories,null=True,blank=True, on_delete = models.CASCADE)
    name = models.CharField(max_length =100)
    seller = models.ForeignKey(Seller, on_delete = models.CASCADE)
    description = RichTextUploadingField()
    brand = models.CharField(max_length = 100, help_text= 'Brand of the product', null=True, blank =True)
    main_image = models.ImageField(upload_to='Product/Main-image/')
    image2= models.ImageField(upload_to='Product/Main-image/')
    image3 =models.ImageField(upload_to='Product/Main-image/', null=True, blank =True)
    image4= models.ImageField(upload_to='Product/Main-image/', null=True, blank =True)
    created_date = models.DateTimeField(auto_now_add = True)
    price = models.DecimalField(max_digits=10, decimal_places = 2)
    discount_price = models.DecimalField(max_digits=10, decimal_places = 2)
    available = models.BooleanField(default =True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product", kwargs={"pk": self.pk})

    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={
            'pk':self.pk
        })
    def get_remove_from_cart_url(self):
        return reverse("remove-from-cart", kwargs={
            'pk':self.pk
        })

class OrderProduct(models.Model):
    user = models.ForeignKey(myuser, on_delete=models.CASCADE)
    ordered= models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def get_total_item_price(self):
        return self.quantity * self.product.price

    def get_discount_item_price(self):
        return self.quantity * self.product.discount_price

    def get_amount_saved(self):
        return self.get_discount_item_price() - self.get_discount_item_price()
    
    def get_discount_rate(self):
       
        num =  (self.product.discount_price / self.product.price)*100
        return round(num,2)
    def get_final_price(self):
        if self.product.discount_price:
            return self.get_discount_item_price()

        return self.get_total_item_price()

DeliveryMethod= (
    ('D', 'Door Delivery'),
    ('P', 'Pickup Station')

)

class Order(models.Model):
    user = models.ForeignKey(myuser, on_delete=models.CASCADE)
    product = models.ManyToManyField(OrderProduct)
    start_date= models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    delivery_method = models.CharField(max_length=100, choices=DeliveryMethod, null=True, blank=True)

    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True
    )    

    def get_total_price(self):
        total = 0
        for order_item in self.product.all():
            total += order_item.get_final_price()

        return total

class Payment(models.Model):
    user = models.ForeignKey(
        myuser, on_delete = models.SET_NULL, blank =True, null=True
    )
    amount= models.FloatField()
    timestamp= models.DateTimeField(auto_now_add=True)


class CustomerAccount(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11, blank=False,null=False)
    additional_phone_number = models.CharField(max_length=11, blank=False,null=False)
    delivery_address = models.CharField(max_length=100, blank=False,null=False)
    additional_info = models.CharField(max_length=100, blank=True,null=True)
    region = models.ForeignKey(Region, on_delete = models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    gender = models.CharField(max_length= 100, choices=Gender, null=True, blank= True)
    birth_date = models.DateField(null=True, blank= True)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'





class SavedItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

App/templates/App/address-book.html
{% extends 'App/index.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/account-book.css' %}">
{% endblock %}

{% block content %}
<section class="account-container">
    <form method="post" class="account-wrapper">
        {% csrf_token %}
        <div class="account-box1">
            <div class="box1-wrapper">
                <div class="box1-items">
                    <i class="fa-regular fa-user"></i>
                    <span>My Jumia Account</span>
                </div>
                <div class="box1-items">
                    <i class="fa-solid fa-bag-shopping"></i>
                    <span>Orders</span>
                </div>
                <div class="box1-items">
                    <i class="fa-solid fa-envelope"></i>
                    <span>Inbox</span>
                </div>
                <div class="box1-items">
                    <i class="fa-solid fa-square-pen"></i>
                    <span>Pending Reviews</span>
                </div>
                <div class="box1-items">
                    <i class="fa-solid fa-heart"></i>
                    <span>Saved Items</span>
                </div>
                <div class="box1-items">
                    <i class="fa-solid fa-trash"></i>
                    <span>Close Account</span>
                </div>
                
                
            </div>
            <div class="Logout">
                <span>Logout</span>
            </div>
        </div>
        <div class="account-box2">
            <div class="title">
                Account Overview
            </div>
           <div class="address-wrapper">
               <div class="address-card1">
                    <div class="card1-items">
                        <div class="box-wrapper right input-card" id="box_first_name">
                            <label for="FirstName">First Name</label>
                           {{form2.first_name}}
                        </div>
                        <div class="box-wrapper input-card" id="box_last_name">
                            <label for="Last Name">Last Name</label>
                            {{form2.last_name}}
                        </div>
                    </div>
                    <div class="card1-items">
                       <input type="hidden" name="user" value="{{request.user.id}}">
                        <div class="box-wrapper right input-card">
                            <label for="Phone Number">Phone Number</label>
                           {{form1.phone_number}}
                        </div>
                        <div class="box-wrapper input-card" >
                            <label for="Additional Phone Number">Additional Phone Number</label>
                            {{form1.additional_phone_number}}
                        </div>
                    </div>
                    
               </div>
               <div class="address-card2">
                <div class="card2-items">
                    <div class="box2-wrapper input-card">
                     
                        <label for="Delivery Address">Delivery Address</label>
                        {{form1.delivery_address}}
                    </div>
                    <div class="box2-wrapper input-card">
                        <label for="Additional Information">Additional Information</label>
                        {{form1.additional_info}}
                    </div>
                    <div class="card1-items">
                        <div class="box-wrapper3 right ">
                            <label for="Country">Country</label>
                            {{form1.region}}
                        </div>
                        <div class="box-wrapper3 ">
                            <label for="City">City</label>
                            {{form1.city}}
                        </div>
                    </div>
                    <div class="card1-items">
                        <div class="box-wrapper3 right ">
                            <label for="Gender">Gender</label>
                            {{form1.gender}}
                        </div>
                        <div class="box-wrapper3">
                            <label for="Date of birth">Date of birth</label>
                           
                            <input type="date" name="birth_date" id="id_birth_date"">
                        </div>
                    </div>
                    <div class="box-btn"><button>Save</button></div>
                </div>
                
               </div>
               
           </div>
        </div>
    </form>
</section>
{% endblock %}

{% block script %}
<script src="{% static 'javascript/address-book.js' %}"></script>
{% endblock %}

App/templates/App/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <form action="">
            <button id="minus">minus</button>
            <input type="text" name="num" value="1" id="num">
            <button id="link">plus</button>
        </form>

    </div>
</body>
<script>
    
    var num = document.getElementById('num');
    var link = document.getElementById('link').addEventListener('click',cartPlus);
    var minus = document.getElementById('minus').addEventListener('click',cartMinus);
    
    function cartPlus(event){
        event.preventDefault();
        val = parseInt(num.value);
        if(val < 100){
        num.value = val + 1;
        }
        else{
        num.value = 100;
        }
    }
    function cartMinus(event){
       event.preventDefault();
       val = parseInt(num.value);
       if(val > 0){
        num.value = val - 1;
       }
       else{
        num.value = 0;
       }
    }

</script>
</html>

App/templates/App/check-out.html
{% extends 'App/index.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/check-out.css' %}">
{% endblock %}

{% block content %}
<section class="check-out">
    <form action="" method="post">
        {% csrf_token %}
        <div class="check-out-wrapper">
            <div class="check-out-card1">
                <div class="check1">
                    <div class="check1-header">
                       <div>
                        <i class="fa-solid fa-circle-check"></i>
                        <span>1. ADDRESS DETAILS</span>
                       </div>
                       <a href="{% url 'create-customer-address' %}">Change</a>
                    </div>
                    <div class="check1-box">
                        <div class="check1-name">{{account.user.first_name}} {{account.user.last_name}}</div>
                        <div class="check1-address">{{account.delivery_address}}, {{account.region}}</div>
                        <div class="check1-ph">{{account.phone_number}}</div> 
                    </div>
                </div>
                <div class="check2">
                    <div class="check1-header">
                        <div>
                         <i class="fa-solid fa-circle-check"></i>
                         <span>2. DELIVERY METHOD</span>
                        </div>
                        <a href=""></a>
                    </div>
                    <div class="check1-box">
                        <div class="check1-name">How do you want your order delivered?</div>
                        <form action="">
                           {{form.delivery_method}}
                            
                        </form>
                       
                    </div>
                </div>
    
                <div class="check2">
                    <div class="check1-header">
                        <div>
                         <i class="fa-solid fa-circle-check"></i>
                         <span>3. PAYMENT METHOD</span>
                        </div>
                        <a href=""></a>
                    </div>
                    <div class="check1-box">
                        <div class="check1-name">Pay with Cards, Bank Transfer or USSD</div>
                           {{form.payment_option}}
                       
                    </div>
                </div>
            </div>
           
            <div class="check-out-card2">
                <div class="cart-box2">
                    <div class="cart-sum">
                        <div class="sum-tile">CART SUMMARY</div>
                        {% for order_item in order.product.all %}
                        <div class="box2-card">
                            <img src="{{ order_item.product.main_image.url }}" alt="">
                            <div class="box2-text">
                                <div class="product-name">{{ order_item.product.name }}</div>
                                <div class="product-price">₦{{ order_item.get_final_price  }}</div>
                                <div class="product-qty">Qty:{{order_item.quantity}}</div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="mod-cart">
                            <a href="{% url 'order-summary' %}">Modify Cart</a>
                        </div>
                        <div class="sub-total">
                            <span>Subtotal</span>
                            <span>₦ {{ order.get_total_price }}</span>
                        </div>
                       <div class="btn">
                        <button type="submit">CHECKOUT ({{ order.get_total_price }})</button>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
{% endblock %}

App/templates/App/checkout-address.html
{% extends 'App/index.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/checkout-address.css' %}">
{% endblock %}

{% block content %}
<section class="check-out">
    <form action="" method="post">
        {% csrf_token %}
        <div class="check-out-wrapper">
            <div class="check-out-card1">
                <div class="account-box2">
                    <div class="title">
                        Delivery Address
                    </div>
                   <div class="address-wrapper">
                       <div class="address-card1">
                            <div class="card1-items">
                               
                            </div>
                            <div class="card1-items">
                               <input type="hidden" name="user" value="{{request.user.id}}">
                                <div class="box-wrapper right input-card">
                                    <label for="Phone Number">Phone Number</label>
                                   {{form1.phone_number}}
                                </div>
                                <div class="box-wrapper input-card" >
                                    <label for="Additional Phone Number">Additional Phone Number</label>
                                    {{form1.additional_phone_number}}
                                </div>
                            </div>
                            
                       </div>
                       <div class="address-card2">
                        <div class="card2-items">
                            <div class="box2-wrapper input-card">
                             
                                <label for="Delivery Address">Delivery Address</label>
                                {{form1.delivery_address}}
                            </div>
                            <div class="box2-wrapper input-card">
                                <label for="Additional Information">Additional Information</label>
                                {{form1.additional_info}}
                            </div>
                            <div class="card1-items">
                                <div class="box-wrapper3 right ">
                                    <label for="Country">Country</label>
                                    {{form1.region}}
                                </div>
                                <div class="box-wrapper3 ">
                                    <label for="City">City</label>
                                    {{form1.city}}
                                </div>
                            </div>
                            <div class="card1-items">
                                <div class="box-wrapper3 right ">
                                    <label for="Gender">Gender</label>
                                    {{form1.gender}}
                                </div>
                                <div class="box-wrapper3">
                                    <label for="Date of birth">Date of birth</label>
                                   
                                    <input type="date" name="birth_date" id="id_birth_date"">
                                </div>
                            </div>
                            <div class="box-btn"><button>Save</button></div>
                        </div>
                        
                       </div>
                       
                   </div>
                </div>
            </div>
           
            <div class="check-out-card2">
                <div class="cart-box2">
                    <div class="cart-sum">
                        <div class="sum-tile">CART SUMMARY</div>
                        {% for order_item in order.product.all %}
                        <div class="box2-card">
                            <img src="{{ order_item.product.main_image.url }}" alt="">
                            <div class="box2-text">
                                <div class="product-name">{{ order_item.product.name }}</div>
                                <div class="product-price">₦{{ order_item.get_final_price  }}</div>
                                <div class="product-qty">Qty:{{order_item.quantity}}</div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="mod-cart">
                            <a href="{% url 'order-summary' %}">Modify Cart</a>
                        </div>
                        <div class="sub-total">
                            <span>Subtotal</span>
                            <span>₦ {{ order.get_total_price }}</span>
                        </div>
                       <div class="btn">
                        <button type="submit">CHECKOUT ({{ order.get_total_price }})</button>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
{% endblock %}
{% block script %}
<script src="{% static 'javascript/address-book.js' %}"></script>
{% endblock %}

App/templates/App/customer-login.html
{% extends 'App/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}


{% block content %}

<div class="body-wrapper">
    <div class="container">
     
        <div class="header-form">
           <!-- <div class="logo">DiasporaBlack</div>-->
            <h1>Welcome</h1>
            <p class="text">Sign up to DiasporaBlack</p>
        </div>
    
        <form action="" method="POST" class="body">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <p style="color: red;font-size: 1.1rem;">{{form.non_field_errors}}</p>
            {% endif %}
            <div class="input-card">
                {{form.username}}
               
                <label for="">Email</label>
            </div>
             <div class="input-card">
                {{form.password}}
               <!-- <div class="eye" onclick="show2()"> <i id="eye1" class="fa-regular fa-eye"></i></div>-->
                <label for="">Password</label>
             </div>
           
    
            <div class="continue-card">
               <a href="" class="forgot">
                <p>Forgot password?</p>
               </a>
               <button type="submit">Continue</button>
               <div class="account">
               Already have an account? <a href="">Login</a>
               </div>
            </div>
    
            <div class="or-card">
                <div class="border"></div>
                <div class="text">OR</div>
            </div>
        </form>
    
        <div class="auth-card">
            <div class="card">
                <a href="">
                   <div class="icon"><i class="fa-brands fa-google"></i></div>
                   <div class="text">Continue with Google</div>
                </a>
            </div>
            <div class="card">
                <a href="">
                    <div class="icon"><i class="fa-brands fa-facebook"></i></div>
                    <div class="text">Continue with Facebook</div>
                 </a>
            </div>
            <div class="card">
                <a href="">
                    <div class="icon"><i class="fa-brands fa-twitter"></i></div>
                    <div class="text">Continue with Twitter</div>
                 </a>
            </div>
        </div>
    
    </div>
    <div id="overlay" onclick="Modal()"></div>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'javascript/signup.js' %}"></script>
{% endblock %}

App/templates/App/payment.html
<body onload="payWithPaystack()">
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
    window.onload=function(){
    payWithPaystack();
    };
    function payWithPaystack(){
    var handler = PaystackPop.setup({
    key: 'pk_test_0b181c36e7107916cf6718810a19af5acdf3e844',
    email:'{{request.user.email}}',
    amount:'{{amount}}',
    currency: "NGN",
    metadata: {
    custom_fields: [
    {
    display_name: "Mobile Number",
    variable_name: "mobile_number",
    value: "{{phone}}"
    }
    ]
    },
    callback: function(response){
        $.ajax({
        type:"GET",
        url:'payment',
        data:{'result':response.reference}
    });
    alert('success. transaction ref is ' + response.reference);
   

    },
    onClose: function(){
    alert('window closed');
    }
    });
    handler.openIframe();
    }
    </script>
   
</body>

App/templates/App/seller-login.html
{% extends 'App/index.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}


{% block content %}

<div class="body-wrapper">
    <div class="container">
     
        <div class="header-form">
           <!-- <div class="logo">DiasporaBlack</div>-->
            <h1>Welcome</h1>
            <p class="text">Sign up to DiasporaBlack</p>
        </div>
    
        <form action="" method="POST" class="body">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <p style="color: red;font-size: 1.1rem;">{{form.non_field_errors}}</p>
            {% endif %}
            <div class="input-card">
                {{form.username}}
               
                <label for="">Email</label>
            </div>
             <div class="input-card">
                {{form.password}}
               <!-- <div class="eye" onclick="show2()"> <i id="eye1" class="fa-regular fa-eye"></i></div>-->
                <label for="">Password</label>
             </div>
           
    
            <div class="continue-card">
               <a href="" class="forgot">
                <p>Forgot password?</p>
               </a>
               <button type="submit">Continue</button>
               <div class="account">
               Don't have an account? <a href="{% url 'seller-signup' %}">Signup</a>
               </div>
            </div>
    
            <div class="or-card">
                <div class="border"></div>
                <div class="text">OR</div>
            </div>
        </form>
    
        <div class="auth-card">
            <div class="card">
                <a href="">
                   <div class="icon"><i class="fa-brands fa-google"></i></div>
                   <div class="text">Continue with Google</div>
                </a>
            </div>
            <div class="card">
                <a href="">
                    <div class="icon"><i class="fa-brands fa-facebook"></i></div>
                    <div class="text">Continue with Facebook</div>
                 </a>
            </div>
            <div class="card">
                <a href="">
                    <div class="icon"><i class="fa-brands fa-twitter"></i></div>
                    <div class="text">Continue with Twitter</div>
                 </a>
            </div>
        </div>
    
    </div>
    <div id="overlay" onclick="Modal()"></div>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'javascript/signup.js' %}"></script>
{% endblock %}